Develop
shekshuev/gophertalk-backend pull request #1
Opened 2024-12-23 20:24 UTC by shekshuev

Реализовал апи, который планировал. Описание в ридми. Пока не применял оптимизации, хотелось бы получить фидбэк на данном этапе. 
Что планирую сделать:
1. Записывать лайки и просмотры батчами, предварительно накопив данные в мапе. 
2. Убрать CTE и join-ы, делать параллельные запросы горутинами. Это поможет избежать обработки в памяти большого количества строк
3. Сделать connection pool для бд
4. Добавить индексы 
5. Сделать реплику базы. Писать в мастер, читать из реплики
6. Сделать материализованное представление с кэшированными данными для самых популярных пользователей. Данные хранить уже в json

2024-12-25 10:48 UTC, Bazys requested changes
1. есть дублирующийся код
2. часто лишние else
3. не увмдел применения какого либо паттерна многопоточности (например в фоне готовим ленту)

2024-12-25 10:48 UTC, Bazys commented on cmd/gophertalk/main.go
> +	} else {
на 43 строке будет os.Exit(1)
зачем else?
и дефер на 41 строке не выполнится

2024-12-25 10:48 UTC, Bazys commented on internal/handler/posts.go
> +	reply_to_id, err := strconv.ParseUint(r.URL.Query().Get("reply_to_id"), 10, 64)
мы не в ПГ, тут нейминг в стиле replyToID

2024-12-25 10:48 UTC, Bazys commented on internal/utils/jwt.go
> +	token, err := jwt.ParseWithClaims(tokenString, claims, func(t *jwt.Token) (interface{}, error) {
Параметр функции, названный `t`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `t` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-12-25 10:48 UTC, Bazys commented on internal/handler/posts.go
> +func (h *Handler) ViewPost(w http.ResponseWriter, r *http.Request) {
повторяющийся код с LikePost
может как то унифицировать?

2025-01-26 20:22 UTC, shekshuev commented
Добавил fan-out/fan-in в GetAllPosts, а также закэшировал лайки и просмотры

2025-01-28 19:06 UTC, merged